### ISSUE TITLE
建议常驻tab来提高生成速度

### ISSUE THREAD

**Issue by Enivel** [xiongwilee/imageTemplateGenerator#4]
通过在模板中注入js 动态加载新图片自动截图, 可以减少puppeteer启动时间, 还可以同时启动n个tab进行并发处理

**Comment by xiongwilee** [comment]
> 通过在模板中注入js 动态加载新图片自动截图

现在是通过requestjs并行请求图片，生成BASE64，测试了下性能是最优的；同时还可以满足本地图片加载的file协议问题

> 还可以同时启动n个tab进行并发处理

这个不太明白你的意思
